### PR TITLE
fix warnings related to string literals assigned to non-const char *

### PR DESCRIPTION
**Pull request by jeking3**
fixes compiler warnings

### CODE REVIEW

**Comment by mclow** [comment]
What compiler warnings does this fix?

**Comment by jeking3** [comment]
In something I merged yesterday, this fixes a C++11 warning about deprecated behavior of assigning a literal string to a "char *" as opposed to a "const char *".

**Comment by mclow** [comment]
Make them `constexpr const` ;-)

**Comment by jeking3** [comment]
Is there a macro for this?  I know of `BOOST_CONSTEXPR_OR_CONST` for C++03 compatibility.

**Comment by mclow** [comment]
How about `BOOST_CONSTEXPR const` ?

**Pull request merged**
